# Generated by Django 4.0.1 on 2022-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('iamge', models.ImageField(upload_to='blog/images')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
