# Generated by Django 4.0.1 on 2022-01-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projec',
            new_name='Project',
        ),
    ]
